version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: choco install golang 7zip -y
      - run: RefreshEnv.cmd
      - run: go build -o falcon.exe .
      - run: 7z a -t7z falcon-windows.7z .\falcon.exe
      - store_artifacts:
          path: falcon-windows.7z
          destination: falcon-windows.7z
  build-linux:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: go build -o falcon .
      - run: tar -czvf falcon-linux.tar.gz ./falcon
      - store_artifacts:
          path: falcon-linux.tar.gz
          destination: falcon-linux.tar.gz

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-windows
      - build-linux
